### ISSUE TITLE
Error when running latest text-generation-inference

### ISSUE THREAD

**Issue by csnelsonchu** [awslabs/extending-the-context-length-of-open-source-llms#1]
Unable to run the latest https://github.com/huggingface/text-generation-inference

```
2023-08-01T22:36:41.651714Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 78, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 184, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 136, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 226, in get_model
    return RW(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/rw.py", line 35, in __init__
    model = AutoModelForCausalLM.from_pretrained(
  File "/opt/conda/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 462, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2493, in from_pretrained
    raise EnvironmentError(
OSError: amazon/FalconLite does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.
``

**Comment by csnelsonchu** [comment]
Also tried the 0.9.2 version, but having the same issue.

**Comment by yinsong1986** [comment]
Can u run this script to download the model to your local machine first? python script/download_model.py

**Comment by yinsong1986** [comment]
BTW: 0.9.2 should work, when switching to 0.9.2, did u re-build the docker image ./docker_build.sh? Thanks!

**Comment by chenwuperth** [comment]
Hi @csnelsonchu thanks for raising the issue. Currently FalconLite won't support latest TGI. As Yin suggested, if you could try rebuilding the docker image using 0.9.2 and let us know how it goes.

**Comment by csnelsonchu** [comment]
@yinsong1986 @chenwuperth 
Thanks for getting back to me, I can get it working on 0.9.2 now.
This is great, thanks.
